### ISSUE TITLE
Subsequent columns sometimes "appear" not to be marked

### ISSUE THREAD

**Issue by nisensee** [thinwire/GridFastNavigation#4]
With this addon comes the feature that columns will be automatically "marked" so the user needs but to type in order to change any given value (instead of deleting it manually).  I noticed that occasionally the next value "appears" not to be highlighted, although it actually is. I tried to capture this hiere:
![invisible mark](https://cloud.githubusercontent.com/assets/2082077/17973198/c838f584-6ae1-11e6-8a68-a4cd5e0a4fca.png)
I initiated the edit mode by "directly typing in a new value" (the 'wasd' in the picture). The second (and sometimes even the third) value will usually not be marked, although they are.
This might be confusing for some.

**Comment by thinwire** [comment]
I can't promise this will ever work, due to the hacky nature of this extension - we're racing the Grid for events as it is. I'll take a look and try to figure out why this happens, though.

**Comment by thinwire** [comment]
I have not seen this behavior in latest master

**Comment by thinwire** [comment]
New version released - please reopen the issue if you find it persists.
