### ISSUE TITLE
Arrow navigation in columns breaks navigation in calendar field

### ISSUE THREAD

**Issue by nisensee** [thinwire/GridFastNavigation#5]
You can chain-edit vertical cells by pressing "up" or "down". The following cell is editable directly. Unfortunately that renders the calendar popup unusable as "down" both opens the popup and switches the row.

**Comment by thinwire** [comment]
Dealing with this situation is a bit difficult - some may not want the calendar popup to show at all and the row to move, while others will want the row to move and the calendar popup to be ignored. Unless there's objections, I'll implement one feature first and make it standard, and then add a programmatic toggle to switch the mode.

**Comment by thinwire** [comment]
This issue has been fixed - currently, the up/down arrow functionality is configurable on a per widget type basis.

**Comment by thinwire** [comment]
Fix released.
